---
- name: Install prerequisite packages
  ansible.builtin.apt:
    name: "{{ cifs_package }}"
    state: present
    update_cache: true
    cache_valid_time: 3600

- name: check mountpoint exist
  ansible.builtin.file:
    path: "{{ mountpoint }}"
    state: directory
    mode: '0755'
    owner: malcolm
    group: malcolm

- name: mount network share
  ansible.posix.mount:
    src: "{{ mycifs }}"
    path: "{{ mountpoint }}"
    fstype: cifs
    opts: 'username={{ username }},password={{ password }},uid=1000,gid=1000,noperm,vers=3.0'
    state: mounted